### ISSUE TITLE
Reconsider --without-all 

### ISSUE THREAD

**Issue by sambrightman** [rejeep/evm#101]
I believe these contribution instructions were likely made in the interest of reducing build times and complexity. Hopefully @DamienCassou can confirm this?

I also believe- but am not confident - that adding TLS support would reduce issues being seen, especially with Emacs 26+. If so, we should re-issue the pretest/snapshot releases (seems totally acceptable for unofficial releases) before a full 26 is released in a way that causes people to struggle or use workarounds. I’ve been installing gnutls-bin in some Travis builds already and that is probably a less than ideal path forward.

**Comment by rejeep** [comment]
The main issue I think is that by default you get a lot of crap when building Emacs that requires dependencies. You are welcome to change this if you find something that works.

**Comment by DamienCassou** [comment]
> I believe these contribution instructions were likely made in the interest of reducing build times and complexity. Hopefully @DamienCassou can confirm this?

`--without-all` was introduced way before I rewrote the instructions. I just copied this part.

**Comment by sambrightman** [comment]
Ok I will have a go at rebuilding the snapshots and reissuing them with TLS support. I’ll want to see if it makes the build harder and whether it fixes common issues.

**Comment by sambrightman** [comment]
Well, this has been an interesting journey. Add GnuTLS support does not seem to overly complicate the build, and I'll file a PR to update the instructions once the below adventures are confirmed to be over:

1. there is an additional issue in both current snapshot releases that `gnutls-available-p` is simply broken for GnuTLS <3, returning `nil`. Rather annoying. New releases will need to move forward in addition to adding the config option.
2. I *believe* elpa.gnu.org is misconfigured, along with a bug/missing feature in the Travis version of GnuTLS - see https://emacs.stackexchange.com/a/38404/3985. That one took even longer to find.

Once confirmed/fixed, will proceed. Currently fixing only 1) will pop up the interactive network security manager, which is only worse than a quick fail.

**Comment by gonewest818** [comment]
Regarding the second issue listed above...  I noticed the same thing when working on a Travis CI setup in the `clojure-emacs/cider` project.  For now it's being handled with a custom script that downloads and compiles a more modern `gnutls` from sources.

See https://github.com/clojure-emacs/cider/pull/2128

And the current version of the [install-gnutls.sh script](https://github.com/clojure-emacs/cider/blob/master/travis-ci/install-gnutls.sh) for reference.

**Comment by sambrightman** [comment]
I’m in touch with gnu.org sysadmins. Hopefully it will be fixed.

**Comment by gonewest818** [comment]
Ok, I’ll keep watching these tickets for news. I’d like to back out the gnutls-bin in Travis for those projects where I’ve introduced it.

**Comment by sambrightman** [comment]
Yeah, I don't think that's the way forward. I also added it in a couple of places, and subsequently also had problems that I think were possibly due to it (looked like files had been cut-off half-way through download). It shouldn't be a requirement for all users to add that.

**Comment by sambrightman** [comment]
@gonewest818 I believe the issue with elpa.gnu.org is fixed now.

I'll wait for confirmation of #103 being fixed, then proceed with this and #102.

**Comment by gonewest818** [comment]
Good to hear.  Did the FSF server admins make an announcement of that change somewhere?

**Comment by sambrightman** [comment]
Not sure what the appropriate place would be but I was CCd on this: http://lists.gnu.org/archive/html/bug-gnu-emacs/2018-02/msg00774.html

**Comment by gonewest818** [comment]
Mailing list is good enough!  I just used the same link in another ticket elsewhere.  Thanks.
