### ISSUE TITLE
Emacs 26.2 released

### ISSUE THREAD

**Issue by sergeyklay** [rejeep/evm#118]
Hello,

Emacs 26.2 released.
Please provide emacs-26.2-travis.

Refs:
- https://lists.gnu.org/archive/html/emacs-devel/2019-04/msg00503.html

**Comment by sambrightman** [comment]
Yes, I have the release ready. Will do it tomorrow.

**Comment by sergeyklay** [comment]
@sambrightman 

Just tested [bnf-mode](https://github.com/sergeyklay/bnf-mode) and it works like a charm

![image](https://user-images.githubusercontent.com/1256298/56660645-9e6d1a80-66a8-11e9-9f34-a3766d69c16c.png)

Thank you!
