### ISSUE TITLE
Travis CI: error while loading shared libraries: libgnutls.so.26

### ISSUE THREAD

**Issue by abo-abo** [rejeep/evm#131]
Here's an example run: https://travis-ci.org/abo-abo/swiper/jobs/611786465.

> /tmp/emacs-git-snapshot-travis/bin/emacs: error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory

Sometimes the job succeeds, sometimes it fails, depending on Emacs version.

**Comment by sambrightman** [comment]
You want `emacs-git-snapshot-travis-linux-xenial` for Xenial.

**Comment by abo-abo** [comment]
Thanks.
