### ISSUE TITLE
Update emacs-git-snapshot-travis and emacs-git-snapshot-travis-linux-xenial

### ISSUE THREAD

**Issue by seagle0128** [rejeep/evm#132]
Now emacs27 support new face attribute `extend`, which has been supported in some packages as well, e.g. `magit` (See https://github.com/magit/magit/commit/891ebdca58ef498ff3b94c8ac2921cc6b72c3d25). But the Emacs in `emacs-git-snapshot-travis` and `emacs-git-snapshot-travis-linux-xenial` seems outdated, so cause the failures.

```
Error: Invalid face attribute name: :extend
```

Please update the binaries accordingly. Thanks!

**Comment by sambrightman** [comment]
`emacs-git-snapshot-travis-linux-xenial` and `emacs-git-snapshot-travis-linux-trusty` are updated. Haven't had time to work on aliases, so `emacs-git-snapshot-travis` is not (yet).

**Comment by seagle0128** [comment]
Thank you
