### ISSUE TITLE
Emacs 28.1

### ISSUE THREAD

**Issue by seagle0128** [rejeep/evm#142]
Emacs 28.1 has been released. See https://lists.gnu.org/archive/html/emacs-devel/2022-04/msg00093.html.
Can you please support it in evm? My CIs need to check for 28. Thanks!

**Comment by sambrightman** [comment]
Yes, will be added soon.

**Comment by sambrightman** [comment]
Sorry for the delay. I haven't got around to migrating the CI system yet, so let me know if you have any problems.

**Comment by seagle0128** [comment]
Thank you!
