### ISSUE TITLE
Suggestion: quicker install method for travis tests

### ISSUE THREAD

**Issue by npostavs** [rejeep/evm#52]
```
  - curl -fsSkL https://github.com/rejeep/evm/archive/master.tar.gz | tar -xzf -
  - export PATH="$PWD/evm-master/bin:$PATH"
```

The [`git clone` method][git] measures 0.88s, vs [grabbing the tarball][tarball] which is only 0.10s.

[git]: https://travis-ci.org/npostavs/config/builds/56822828
[tarball]: https://travis-ci.org/npostavs/config/builds/56824216

**Comment by rejeep** [comment]
It's probably a good idea, but I wont change this now. It's not backwards compatible as it changes the path. But I'll leave this issue open and if I make a new major release, I will take this into consideration.

**Comment by npostavs** [comment]
You could add `mv evm-master ~/.evm` to keep the same path. Though I was thinking the lack of git repository would be more of an obstacle to compatibility.

**Comment by rejeep** [comment]
Closing this as it seems no one else has issues with performance. The new Evm master downloads releases from S3, so it should be pretty quick.
