### ISSUE TITLE
Precompile 24.5 missing

### ISSUE THREAD

**Issue by jorgenschaefer** [rejeep/evm#53]
[Emacs 24.5 was released](http://thread.gmane.org/gmane.emacs.devel/185268%0A) a few days ago. The [evm-bin](https://github.com/rejeep/evm-bin/) project is missing binaries for it.

Any idea when you will be able to compile it for EVM? Also, is there any way someone else might help?

**Comment by rejeep** [comment]
I have started working on this. Had to install a VM etc... but it should be available soon. You could help by testing it once released.

**Comment by jorgenschaefer** [comment]
Thank you! :-)

**Comment by rejeep** [comment]
Crap: https://travis-ci.org/rejeep/evm/jobs/58492185

Unfortunately, I need Ubuntu 12.04 and compile Emacs on that for it to work on Travis. But it's a lot of pain installing that version now as it's quite old. Perhaps it's possible to download a Travis VM, dunno though, but it would be awesome?

If anyone has a working installation of Ubuntu 12.04 and can compile Emacs on it, that would be a bit help.

**Comment by jorgenschaefer** [comment]
Shouldn't the default `vagrant init hashicorp/precise64` get a 12.04 still?

Apparently, Travis supports building Vagrant boxen, too: https://github.com/travis-ci/travis-cookbooks

A simple `vagrant up` there got me a working Travis box:

```
vagrant@vagrant-ubuntu-precise-64:~$ lsb_release -d
Description:	Ubuntu 12.04.5 LTS
```

Do you want me to compile Emacs 24.5 in there?

**Comment by rejeep** [comment]
I have never used Vagrant, but that sounds pretty darn awesome! I will check it out and see if I can get it running.

**Comment by rejeep** [comment]
Well that was a brilliant move, thanks for the tip! :)

I've added Emacs 24.5, please try it out and report back if you have any issues with it.

**Comment by rejeep** [comment]
I tested it on `f.el` and it seemed to work. Getting some warnings though, but I get those for 24.4 as well.

**Comment by jorgenschaefer** [comment]
I get this error on all my builds:

```
Warning: arch-dependent data dir `/usr/local/evm/emacs-24.5/libexec/emacs/24.5/x86_64-unknown-linux-gnu/': No such file or directory
Warning: arch-independent data dir `/usr/local/evm/emacs-24.5/share/emacs/24.5/etc/': No such file or directory
Warning: Lisp directory `/usr/local/evm/emacs-24.5/share/emacs/24.5/lisp': No such file or directory
Error: charsets directory not found:
/usr/local/evm/emacs-24.5/share/emacs/24.5/etc/charsets
Emacs will not function correctly without the character map files.
Please check your installation!
```

E.g. here: https://travis-ci.org/jorgenschaefer/emacs-buttercup/jobs/58499096

I've never seen that error. Strange.

**Comment by rejeep** [comment]
Can you please restart that build. I had mistakenly named the directory. I got this on `f.el` as well, but not anymore.

**Comment by jorgenschaefer** [comment]
Confirmed, all my packages build fine with the pre-built 24.5. Thank you very much for all your work! :-)

**Comment by rejeep** [comment]
Thank you, your input made it a lot easier for me! :)
