### ISSUE TITLE
Does http_proxy environment variable supported?

### ISSUE THREAD

**Issue by proofit404** [rejeep/evm#56]

**Comment by rejeep** [comment]
What do you mean?

**Comment by proofit404** [comment]
Sorry for cumbersome question.
I mean if I set environment variable `export http_proxy=http://corporative.gateway:3128` does `evm` download Emacs sources or binaries with respect to this var? Currently I got timeout every time I try to use `evm` from my job office.

**Comment by rejeep** [comment]
No idea? Is that some kind of ruby standard?

**Comment by proofit404** [comment]
I'm not quiet sure this is mandatory. Some soft respect it. Some doesn't. But its more like a convention. For example python `pip`, `wget` and clojure `lein` have to use this variable. Debian `aptitude` doesn't use this variable (I think this is security issue in this case). I'm not familiar with ruby standards, so I can't answer your question directly.

Is there another way to use evm behind proxy?

**Comment by rejeep** [comment]
Seems some libraries in Ruby are using the `HTTP_PROXY` environment variable. If you want to implement this, I'm fine with merging it!

**Comment by rejeep** [comment]
Closing this as nothing has happened.
