### ISSUE TITLE
/tmp install

### ISSUE THREAD

**Issue by phillord** [rejeep/evm#57]
It would be nice to support a /tmp install mechanism, in addition to the current /usr/local/evm. This would allow non-sudo installation, while still supporting the requirement for a standardised location for install. I realise that this would require duplication of the binaries.

My use case for this is, basically, travis-ci which needs a sudo less build!

**Comment by rejeep** [comment]
It would be possible to support this for non binaries without much fuzz.

**Comment by jorgenschaefer** [comment]
I came across the same issue. Travis recently switched to a container-based infrastructure which [requires non-sudo uses](http://docs.travis-ci.com/user/migrating-from-legacy/).

As is, I can see two possible approaches here. First is to install from source with a custom directory, and use the directory caching of Travis here. Second would be for evm to provide Travis-specific binaries. Considering Travis is such a large use case for evm, that might be possible, but I understand the workload is annoying. :-)

A recipe for using evm with Travis correctly either way would be nice.

**Comment by bmag** [comment]
:+1: this affects me too

**Comment by rejeep** [comment]
Well, the `-bin` files are actually built with the same VM that Travis is using, but they should work on other platforms as well. I think running specs in Travis should be fast, so I vote for creating `-travis` binaries.

The only issue with adding such binaries is that they are stored on Github (see https://github.com/rejeep/evm-bin) and I will soon hit the maximum size allowed for a repo. One way would be to create a new repo `evm-travis`.

If anyone is up for the task of building all these binaries and adding recipes, let me know and I will create the repo.

**Comment by npostavs** [comment]
> The only issue with adding such binaries is that they are stored on Github (see https://github.com/rejeep/evm-bin) and I will soon hit the maximum size allowed for a repo.

Maybe it's better to store them as "releases"? https://help.github.com/articles/distributing-large-binaries/

> If you need to distribute large files within your repository, we recommend that you create releases for your projects on GitHub. Releases allow you to include binary files, such as compiled programs. For more information, visit "Creating releases."

> We don't limit the total size of your binary release files, nor the bandwidth used to deliver them. However, each individual file must be under 2GB in size.

**Comment by rejeep** [comment]
:+1:

**Comment by DamienCassou** [comment]
Any progress on this? We can't use the new travis infrastructure because of the sudo-less requirement.

**Comment by rejeep** [comment]
@DamienCassou If I try this out for one Emacs version, could you help me with the testing?

**Comment by DamienCassou** [comment]
Johan Andersson <notifications@github.com> writes:

> @DamienCassou If I try this out for one Emacs version, could you help me with the testing?

obviously :-). I'm on IRC #emacs if you want.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by rejeep** [comment]
@DamienCassou See https://github.com/rejeep/evm/pull/59

Can you please try to install that branch of evm and install `emacs-24.5-travis` on Travis!?

**Comment by DamienCassou** [comment]
@rejeep https://github.com/DamienCassou/beginend/pull/2

**Comment by rejeep** [comment]
I think the [gist script](https://gist.githubusercontent.com/DamienCassou/f7d324c72cad63de484d/raw) is still installing `master` of evm, right!?

**Comment by DamienCassou** [comment]
@rejeep you are right. New version: https://travis-ci.org/DamienCassou/beginend/builds/84510060

**Comment by rejeep** [comment]
Right. Gonna have to do some more work here... https://github.com/rejeep/evm/blob/master/lib/evm/cli.rb

**Comment by rejeep** [comment]
The path `/usr/local/evm` is hardcoded in a few places. :cry:

**Comment by rejeep** [comment]
@DamienCassou I did a WIP commit to the branch that adds a `config` command. It was the easiest and most elegant solution I could come up with. This would also allow the user to switch between different installation paths.

So when evm is installed, simply run the command:

```bash
$ evm config path /tmp
```

**Comment by rejeep** [comment]
Seems to be some issues with downloading the release files. Investigating...

**Comment by rejeep** [comment]
@DamienCassou Seems to be working now (see https://travis-ci.org/rejeep/f.el/builds/84626033). Can you try it out again please.

**Comment by DamienCassou** [comment]
@rejeep nope: https://travis-ci.org/DamienCassou/beginend/builds/84510060

**Comment by rejeep** [comment]
Ok, good. That's the first step. Now I just have to build binaries for the other versions, fix the WIP work and then release a new version of Evm. Will let you guys now when I'm done.

**Comment by DamienCassou** [comment]
@rejeep thanks. I've just migrated all my .travis.yml to EVM infrastructure!

**Comment by DamienCassou** [comment]
@rejeep what about all these "Source file `/tmp/emacs-24.5-travis/share/emacs/24.5/lisp/...' newer than byte-compiled file"

**Comment by rejeep** [comment]
Separate issue: https://github.com/rejeep/evm/issues/58

**Comment by rejeep** [comment]
Added binaries for 24.{1..5}. Can you please try them out?!

**Comment by rejeep** [comment]
Also, it would be great if someone could take a look at: https://github.com/rejeep/evm/pull/59

**Comment by rejeep** [comment]
See https://gist.github.com/rejeep/ebcd57c3af83b049833b for a new Evm+Cask+Travis script.

**Comment by rejeep** [comment]
@DamienCassou Add `(source 'gnu)` to your `Cask`-file. `cl-lib` is not included in < Emacs 24.3

**Comment by jorgenschaefer** [comment]
Confirming that the new install script and infrastructure works like a charm – four projects happily ported. Thanks a lot to all of you for the effort!

For others looking for a ready-made solution here, this works:

```yaml
language: emacs-lisp
sudo: no
env:
  - EVM_EMACS=emacs-24.1-travis
  - EVM_EMACS=emacs-24.2-travis
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  - cask
script:
  - ... run your tests here ...
```

**Comment by rejeep** [comment]
@jorgenschaefer Awesome, thanks! Will merge this soon as it seems to work out nicely for people. :+1:

**Comment by rejeep** [comment]
@jorgenschaefer Btw, I would recommend using `generic` as language. See https://github.com/travis-ci/travis-ci/issues/1201

**Comment by jorgenschaefer** [comment]
Updated, thanks :-)

**Comment by rejeep** [comment]
Alright lads, the branch is merged to master. Let me know if there are any issues. Thanks for the input!

**Comment by DamienCassou** [comment]
Thank you so much

**Comment by phillord** [comment]
Also, many thanks!
