### ISSUE TITLE
Add 25.0.* pre-release

### ISSUE THREAD

**Issue by phillord** [rejeep/evm#69]
Would be good to have a pre-release package available!

**Comment by rejeep** [comment]
Is that the same thing as [emacs-git-snapshot-travis](https://github.com/rejeep/evm/blob/master/recipes/emacs-git-snapshot-travis.rb)?

**Comment by phillord** [comment]
I don't think so, no. This is coming from master?

The pre-releases are from the emacs-25 branch. The latest tag is emacs-25.0.94 (and this gets bumped periodically). The pre-releases could do with all the testing that they can get, before the Emacs-25 release.

**Comment by rejeep** [comment]
Ok, so then we would need to create `emacs-git-pre` and `emacs-git-pre-travis`. Are you up for it?

**Comment by phillord** [comment]
I would call them `emacs-25-prerelease` I think. They don't need to come from git (there are tarballs). Then I could add this to my travis as a version, and not have to update it client side when new releases come out. 

Yes, I can do this, if it's a matter of copying the existing ones!

**Comment by rejeep** [comment]
How does the Emacs pre release schema work? How many are there (roughly) before a release for example? Once a version has been released, I guess there's no point in keeping these? That's why I suggested a "git pre", which is the currently active prerelease.

**Comment by phillord** [comment]
There are currently 4 pre-releases, as I've taken them from the tar ball rather than direct from git (my motivation was to skip the byte-compilation, but evm seem to be doing this anyway). Not sure how many more there will be -- probably 2 or 3.

So, yes, having a single "emacs-25-pre" would make sense also. Which ever you prefer.

**Comment by rejeep** [comment]
Let's close this and continue the discussion over at #70
