### ISSUE TITLE
Gem installation misses the bin directory

### ISSUE THREAD

**Issue by wasamasa** [rejeep/evm#77]
I'm using gem with rbenv and tried installing evm, but to my surprise, it didn't add a `rvm` command.  After checking my locally installed files, I've noticed that there is indeed no bin directory there.  Looks like you forgot specifying it in `evm.gemspec`.

Thas aside, the file mentions version 0.9.0, but the gem website doesn't list it.  Perhaps you still need to push a new version for it to be published?

**Comment by rejeep** [comment]
Why would Evm add a `rvm` command? Or did you misspell?

**Comment by wasamasa** [comment]
Sorry, I meant `evm` there.

**Comment by rejeep** [comment]
I guess not too many people use Evm via Rubygems. I added the binary and released a new gem version, can you please try again?

**Comment by wasamasa** [comment]
Nice, that gives me both the binary and an updated version.
