### ISSUE TITLE
evm as installed via gem does not list any recipes

### ISSUE THREAD

**Issue by wasamasa** [rejeep/evm#78]
After installing evm 0.9.0 via `gem install evm`, `evm list` does not list anything.  I've checked the installed files and it appears the recipes directory is absent, so perhaps that needs to be included in `evm.gemspec` as well...

**Comment by rejeep** [comment]
Right. Can you please try v0.9.1?

**Comment by wasamasa** [comment]
Thanks, that did the trick!

**Comment by rejeep** [comment]
Awesome! 👍
