### ISSUE TITLE
Is gemfile.lock needed?

### ISSUE THREAD

**Issue by JJ** [rejeep/evm#79]
It's actually (re) generated every time you do bundle install...

**Comment by rejeep** [comment]
How else would you guarantee to always get the same version of rspec (in this case)?

**Comment by JJ** [comment]
I'm no expert in Ruby, but you can set that in the Gemfile, right?
Gemfile.lock is generated after everything is installed with the versions
that have been actually downloaded for everything.

**Comment by sambrightman** [comment]
`Gemfile.lock` is intentional, as @rejeep describes.
