### ISSUE TITLE
Emacs 25.2 builds do not work

### ISSUE THREAD

**Issue by DamienCassou** [rejeep/evm#86]
Here is the error message (see [for example](https://github.com/DamienCassou/hierarchy/pull/36)):

```
$ evm install $EVM_EMACS --use --skip

Successfully installed emacs-25.2-travis

$ cask

Warning: arch-dependent data dir '/home/travis/builds/emacs-25.2-travis/libexec/emacs/25.2/x86_64-unknown-linux-gnu/': No such file or directory

Warning: arch-independent data dir '/home/travis/builds/emacs-25.2-travis/share/emacs/25.2/etc/': No such file or directory

Warning: Lisp directory '/home/travis/builds/emacs-25.2-travis/share/emacs/25.2/lisp': No such file or directory

Error: charsets directory not found:

/home/travis/builds/emacs-25.2-travis/share/emacs/25.2/etc/charsets

Emacs will not function correctly without the character map files.

Please check your installation!

The command "cask" failed and exited with 1 during .
```

**Comment by rejeep** [comment]
Did you build with the correct prefix path?

**Comment by DamienCassou** [comment]
I did exactly what I wrote in https://github.com/rejeep/evm/pull/85. Are you saying the fact that I switched from `/tmp` to `/home/travis/builds` is the problem? Should I build a new image then?

**Comment by DamienCassou** [comment]
I uploaded a new build on http://damien.cassou.free.fr/emacs-25.2-travis.tar.gz with `--prefix=/tmp/emacs-25.2-travis`

**Comment by rejeep** [comment]
> Are you saying that the fact that I switched from /tmp to /home/travis/builds is the problem?

At least it's *a* problem. You must put the files in the same directory as the prefix path.

**Comment by rejeep** [comment]
I uploaded your latest file, can you try again?

**Comment by DamienCassou** [comment]
This time it works perfectly fine: https://github.com/DamienCassou/hierarchy/pull/36.

**Comment by rejeep** [comment]
Good stuff! 👍

**Comment by DamienCassou** [comment]
Should this be closed now?

**Comment by rejeep** [comment]
Yes, if it works!
