### ISSUE TITLE
travis-evm-cask.sh doesn't work on travis

### ISSUE THREAD

**Issue by etu** [rejeep/evm#93]
The shellscript linked in the README doesn't work on travis.

It seems like Cask have upgraded to use Emacs 24.4? And the script linked (https://gist.github.com/rejeep/ebcd57c3af83b049833b) installs 24.3.

I tried to sed-replace it on build to be 24.4 without any success.

I would suggest to put this file in this or cask's repo so one can create a link to the version from master. That way the link doesn't change and doesn't start breaking the build all of a sudden.

**Comment by etu** [comment]
Finally managed to get it running again: https://github.com/etu/webpaste.el/commit/157d524b71786a3d33cbbb31b0eb3a2313185afd

Any idea why cask really needs me to specify the environment variable EMACS everywhere it's used?

**Comment by rejeep** [comment]
Cask just needs some Emacs. Either in `PATH`, or using the `EMACS` env var. I don't really know if anything has changed that would cause this. Seems your issue is solved so I'm closing.
