### ISSUE TITLE
evm fails to build Emacs 24.1

### ISSUE THREAD

**Issue by raxod502** [rejeep/evm#94]
I attempted to install Emacs 24.1 on macOS 10.11 using `evm` from RubyGems, and received the following error during build:

```
Wrong type argument: listp, 35183699949860
```

The command I used was:

```
$ evm install --use emacs-24.1
```

The full build output (many thousand lines) is [here](https://gist.github.com/raxod502/d848cb648c660570a20f023bea5dd894).

The installation sequence was:

```
$ brew install ruby
$ gem install evm
```

`evm` does not appear to know its version:

```
$ evm --version
evm: version unknown
```

My system information is:

```
                    'c.          raxod502
                 ,xNMM.          -------------------------------
               .OMMMMo           OS: OS X El Capitan 10.11.6 15G1611 x86_64
               OMMM0,            Model: MacBookPro11,3
     .;loddo:' loolloddol;.      Kernel: 15.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 5 days, 13 hours, 36 minutes
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 410
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.4.2
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3008x1692@2x, 1440x900@2x
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Kwm
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   CPU: Intel i7-4980HQ (8) @ 2.80GHz
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   GPU: Intel Iris Pro, NVIDIA GeForce GT 750M
    kMMMMMMMMMMMMMMMMMMMMMMd     Memory: 4366MiB / 16384MiB
     ;KMMMMMMMWXXWMMMMMMMk.
       .cooc,.    .,coo:.
```

Interestingly, the precise integer (`35183699949860`) is the same every time.

**Comment by rejeep** [comment]
No idea why that happens, sorry. Not much to go on given that message and no stacktrace. I guess it has something to do with your environment. Can you try to compile Emacs without Evm and see what happens? I guess the same error should occur.

**Comment by raxod502** [comment]
Unfortunately I was unable to build Emacs 24.1 from source due to [dependency issues](https://github.com/Homebrew/homebrew-core/issues/21826).

**Comment by raxod502** [comment]
Unless someone else has the same problem, it is probably sensible to just close this issue.
